"""Convert the VIA 2.0.8 polygon annotations in data/ into an Ultralytics YOLO dataset.

Input (see data/README.md):
    data/<split>/cats-annotations.json      VIA project export, polygon regions with region_attributes.Class
    data/<split>/<Class>/<filename>         images

Output (rebuilt from scratch on every run):
    datasets/cats/images/{train,val}/<class folder>_<filename>
    datasets/cats/labels/{train,val}/<class folder>_<filename stem>.txt
    datasets/cats/cats.yaml

Image names are prefixed with their class folder because the validation frame names collide between folders
(Blacky/frame220.jpg and Niche/frame220.jpg are different images).

    python tools/via_to_yolo.py                    # detection labels (class cx cy w h)
    python tools/via_to_yolo.py --task segment     # polygon labels (class x1 y1 x2 y2 ...)
"""
import argparse
import json
import shutil
from collections import Counter
from pathlib import Path

from PIL import Image

REPO_ROOT = Path(__file__).resolve().parent.parent

# Class names in label-index order. Append new classes at the end so existing indices stay valid.
CLASSES = ["Blacky", "Niche"]

# YOLO split name -> folder under data/
SPLITS = {"train": "train", "val": "validation"}

ANNOTATION_FILE = "cats-annotations.json"


def find_image(split_dir: Path, filename: str, size: int) -> Path:
    """Locate an annotated image in the class folders of a split.

    VIA identifies images by file name + file size, and names repeat across class folders, so match both.
    """
    matches = [
        p
        for p in sorted(split_dir.glob(f"*/{filename}"))
        if p.stat().st_size == size
    ]
    if len(matches) != 1:
        raise FileNotFoundError(f"expected one image {filename} ({size} bytes) in {split_dir}, found {matches}")
    return matches[0]


def polygon_points(region: dict, width: int, height: int) -> list[tuple[float, float]]:
    shape = region["shape_attributes"]
    if shape["name"] != "polygon":
        raise ValueError(f"unsupported VIA shape: {shape['name']}")
    return [
        (min(max(x, 0), width), min(max(y, 0), height))
        for x, y in zip(shape["all_points_x"], shape["all_points_y"])
    ]


def label_line(class_id: int, points: list[tuple[float, float]], width: int, height: int, task: str) -> str:
    if task == "segment":
        coords = " ".join(f"{x / width:.6f} {y / height:.6f}" for x, y in points)
        return f"{class_id} {coords}"
    xs, ys = [x for x, _ in points], [y for _, y in points]
    x1, x2, y1, y2 = min(xs), max(xs), min(ys), max(ys)
    if x2 <= x1 or y2 <= y1:
        raise ValueError(f"degenerate box {x1, y1, x2, y2}")
    cx, cy = (x1 + x2) / 2 / width, (y1 + y2) / 2 / height
    w, h = (x2 - x1) / width, (y2 - y1) / height
    return f"{class_id} {cx:.6f} {cy:.6f} {w:.6f} {h:.6f}"


def convert_split(split: str, split_dir: Path, out_dir: Path, task: str) -> Counter:
    via = json.loads((split_dir / ANNOTATION_FILE).read_text(encoding="utf-8"))
    images_dir = out_dir / "images" / split
    labels_dir = out_dir / "labels" / split
    images_dir.mkdir(parents=True)
    labels_dir.mkdir(parents=True)

    counts = Counter()
    for key, entry in sorted(via.items()):
        if key.startswith("_via_"):
            continue
        source = find_image(split_dir, entry["filename"], entry["size"])
        with Image.open(source) as image:
            width, height = image.size

        lines = []
        for region in entry["regions"]:
            class_name = region["region_attributes"]["Class"]
            lines.append(label_line(CLASSES.index(class_name), polygon_points(region, width, height), width, height, task))
            counts[class_name] += 1

        name = f"{source.parent.name.lower()}_{source.name}"
        shutil.copy2(source, images_dir / name)
        # An empty label file marks a background image (no objects), which YOLO uses as a negative.
        (labels_dir / name).with_suffix(".txt").write_text("\n".join(lines) + ("\n" if lines else ""), encoding="utf-8")
        counts["images"] += 1
    return counts


def write_dataset_yaml(out_dir: Path) -> Path:
    yaml_path = out_dir / f"{out_dir.name}.yaml"
    lines = [
        "# Generated by tools/via_to_yolo.py - do not edit, re-run the script instead.",
        f"path: {out_dir.resolve().as_posix()}",
        "train: images/train",
        "val: images/val",
        "names:",
        *(f"  {i}: {name}" for i, name in enumerate(CLASSES)),
    ]
    yaml_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return yaml_path


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--data", type=Path, default=REPO_ROOT / "data", help="folder with the VIA splits")
    parser.add_argument("--out", type=Path, default=REPO_ROOT / "datasets" / "cats", help="output dataset folder")
    parser.add_argument("--task", choices=["detect", "segment"], default="detect")
    args = parser.parse_args()

    out_dir = args.out.resolve()
    if out_dir == REPO_ROOT or out_dir in args.data.resolve().parents or out_dir == args.data.resolve():
        parser.error(f"refusing to overwrite {out_dir}")
    if out_dir.exists():
        shutil.rmtree(out_dir)

    for split, folder in SPLITS.items():
        counts = convert_split(split, args.data / folder, out_dir, args.task)
        per_class = ", ".join(f"{name}: {counts[name]}" for name in CLASSES)
        print(f"{split:5} {counts['images']:4d} images | {per_class}")
    print(f"dataset: {write_dataset_yaml(out_dir)}")


if __name__ == "__main__":
    main()
